apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhdh-rc-17-go-github-tekton-quay-jvzmleqz-gitops
  description: This is GitOps manifest for rhdh-rc-17-go-github-tekton-quay-jvzmleqz   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rhdh-rc-17-go-github-tekton-quay-jvzmleqz
    backstage.io/kubernetes-id: rhdh-rc-17-go-github-tekton-quay-jvzmleqz 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rhdh-rc-17-go-github-tekton-quay-jvzmleqz
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rhdh-rc-17-go-github-tekton-quay-jvzmleqz
