apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhdh-rc-17-go-github-tekton-quay-jvzmleqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdh-rc-17-go-github-tekton-quay-jvzmleqz 
  name: rhdh-rc-17-go-github-tekton-quay-jvzmleqz
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhdh-rc-17-go-github-tekton-quay-jvzmleqz
    weight: 100 
